### ISSUE TITLE
Can't use proxies with username and password

### ISSUE THREAD

**Issue by PrintedScript** [noahcoolboy/funcaptcha#10]
I am trying to use proxies which needs authentication with username and password ( username:password@ip:port ) but whenever I try I get the error 

> Proxy response !== 200 when HTTP Tunneling

**Comment by PrintedScript** [comment]
Is there any ETA on when this feature will be added? I am currently using proxyscrape residential proxy pool and they only support username and password authentication

**Comment by noahcoolboy** [comment]
Sorry I just kinda forgot
It has been added, and can be done by putting the authentication in the proxy url like so `http://username:password@host:port`
