### ISSUE TITLE
Encryption Key Failure

### ISSUE THREAD

**Issue by yourmomisgay69420** [noahcoolboy/funcaptcha#12]
When fetching the first image, I am commonly getting an encrypted image response. Looking into this, it appears as though the request to get the encryption key is failing.
The response body will randomly return as {"error":"DENIED ACCESS"} with a status code of 200, even when I have not recently made a request to get the encryption key. Any further attempts to get the encryption key are also unsuccessful with the same response until a new captcha is generated.

**Comment by noahcoolboy** [comment]
This is an issue with arkose labs not being able to generate the images in time (I believe)
This is not something I can fix
But you can add a delay before using getImage for the first time if the problem persists
