### ISSUE TITLE
Where to get solution string?

### ISSUE THREAD

**Issue by 100FIRELTD** [noahcoolboy/funcaptcha#13]
I can't seem to figure out how to get the solution string from your program. I need the actual solution string. Usually looks something like this:

757631cbc10141381.8457708605|r=eu-west-1|metabgclr=transparent|guitextcolor=%23000000|metaiconclr=%23555555|meta=3|meta_height=523|meta_width=558|pk=2CB16598-CB82-4CF7-B332-5990DB66F3AB|at=40|cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-eu-west-1.arkoselabs.com|surl=https%3A%2F%2Fclient-api.arkoselabs.com|smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager

**Comment by noahcoolboy** [comment]
getToken will return an object which has a token property
That's what you need
