### ISSUE TITLE
Signup Detection

### ISSUE THREAD

**Issue by yourmomisgay69420** [noahcoolboy/funcaptcha#14]
Using the signup key for Roblox will result in 20 waves of pick the striped sphere and brick cube (or other variations of that captcha) when using the website on the same IP will result in picking objects.

**Comment by r0wans** [comment]
> Using the signup key for Roblox will result in 20 waves of pick the striped sphere and brick cube (or other variations of that captcha) when using the website on the same IP will result in picking objects.

wtf do you mean

**Comment by yourmomisgay69420** [comment]
![image](https://user-images.githubusercontent.com/101905422/191860128-84ef62c3-2da1-4ac6-9bb8-8b56cf5e1e80.png)

**Comment by Kyurem102** [comment]
Yeah it's from funcaptcha updating their bda everytime
