### ISSUE TITLE
DENIED ACCESS ISSUE

### ISSUE THREAD

**Issue by kencun** [noahcoolboy/funcaptcha#19]
It kept saying denied access when trying to get a token for a roblox auth app.

![image](https://user-images.githubusercontent.com/89197978/208278583-b4bb2dce-59fc-4ff1-8f2e-7fc725f20dfc.png)

**Comment by noahcoolboy** [comment]
Add a delay before getting a token, arkose labs is unable to register the blob in time

**Comment by caycun** [comment]
I tried adding a 10 seconds delay using setTimeout but I'm still getting denied access.
