### ISSUE TITLE
challange.answer() isnt working

### ISSUE THREAD

**Issue by galxy265122** [noahcoolboy/funcaptcha#23]
Challange.answer() is not working

The captcha: 
![image](https://user-images.githubusercontent.com/43180248/211171535-97165c1a-1c8b-4748-b08d-da3b9583e790.png)

The answer:
![image](https://user-images.githubusercontent.com/43180248/211171547-dd182936-1002-4263-b632-db3e5ecf0d68.png)

The code:
![image](https://user-images.githubusercontent.com/43180248/211171558-9ae4e9e1-cad1-4057-9303-d6f7472f2c63.png)

**Comment by noahcoolboy** [comment]
Could you please provide some more info?
Which public_key / surl are you using, and for which website is it?
How many waves are you getting?
Have you answered each wave using the correct number from 0-5?
