### ISSUE TITLE
being served impossible captchas

### ISSUE THREAD

**Issue by brandoge91** [noahcoolboy/funcaptcha#24]
hey 👋 

ive been running a project using this library for a few months, but recently ive been getting reports of roblox sending impossible captchas to my users, is there a way around this, or is it just a side effect of using the libray?

**Comment by noahcoolboy** [comment]
From what I can see, the latest version is able to give working captchas just fine
Could you please provide more context?

![image](https://user-images.githubusercontent.com/46800081/211191331-f9ccd005-c6e1-4b60-90d0-3f2a63d6b57b.png)

**Comment by brandoge91** [comment]
I may need to just update, thanks.

**Comment by brandoge91** [comment]
Yep, this fixed it.
