### ISSUE TITLE
callback function

### ISSUE THREAD

**Issue by vvazharksi** [noahcoolboy/funcaptcha#25]
Hi there, hope it's fine to ask here, how do you invoke funcaptcha callback function without button to return the answer ? 

Trying to capture the flow I have observed that it's bootstrap function but seems impossible to understand what this function is expecting to successfully call it...

**Comment by noahcoolboy** [comment]
I'm not sure what you mean, could you please rephrase your question?

**Comment by vvazharksi** [comment]
So once I have the answer returned for the funcaptcha, I need to use it on the targeted website. I am getting captchas which are with no submit button for the answer.  It's using iframe with callback function but it's unclear how to use the funcaptcha answer, so my question is how to do it or any suggestions how to identify the necessary?

**Comment by SwenenzY** [comment]
You can use promises and recursive loop until solved captcha 

captcha.answer -> returning solved: true
