### ISSUE TITLE
error: 'DENIED ACCESS'

### ISSUE THREAD

**Issue by LightnerDev** [noahcoolboy/funcaptcha#26]
I can't get the code to generate a captcha. Please provide any working examples if there are.

Code:
```js
        const token = await fun.getToken({
            pkey: pkeys.funCaptchaPublicKeys.ACTION_TYPE_GROUP_JOIN, // 63E4117F-E727-42B4-6DAA-C8448E9B137F    From: https://apis.rbxcdn.com/captcha/v1/metadata
            surl: "https://roblox-api.arkoselabs.com"
        })

        console.log(token)
        const session = new fun.Session(token)
```
Error: 
```
{ error: 'DENIED ACCESS' }
/home/lightner/Node-Projects/RobloxAPI/node_modules/funcaptcha/lib/session.js:28
        if (!this.token.startsWith("token="))
                        ^
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new Session (/home/lightner/Node-Projects/RobloxAPI/node_modules/funcaptcha/lib/session.js:28:25)
    at /home/lightner/Node-Projects/RobloxAPI/index.js:21:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by noahcoolboy** [comment]
For roblox, the blob needs to be passed to arkose labs
From the code you provided it doesn't seem like you're doing that

**Comment by LightnerDev** [comment]
How do I get the blob?

**Comment by SwenenzY** [comment]
Blob must be in associated page like this they are storing value at hidden divs or input just search in page 

// example 
const $ = cheerio.load( response.data );
this.arkose_blob = $( "#capture-arkose" ).attr( "data-arkose-exchange-data" );
console.log( "Arkose : " + this.arkose_blob );

// EXAMPLE
arkose blob : wfHfuHvfutYb7hTHyYFFQg==.ZVrm5iSrNNE2InxLqL6D0zpfmcoO0IDDMnAzKQXFxNu6T05rsV+ulNZSU02gqiQltoGyMBl6HorGFmVsWImWw5x0gB2lk7l/gH1Aqb5/5d/lR69l0b0uOOBMoBwlgbsgSg2Uzk+3WqKdAwpRp06TWJCwYDW8unf09Sj7feh0eQsoHDf/a+d7Hq9yW/0FSbOMOI0VEKcqtEYyzFD9DWcjgwDK1s6eM9+on1XDi9LhaxckLk8WYJVkXTBH9Yme8ymxzGOMdeeGfvkPFCcsSmxD/T14lM6mbDKUDS6YppItquJ9WgAdo/bqdTcGL8I4qfL7COVZ7Igz2wo3KgOCkhL9VkxICC7T8iJd13D1HsLX1yTxrsYIkXBNlu+LdLgsacWb/JEvVQJBVqQ9GZLgomVJP4YJkwPn
wfHfuHvfutYb7hTHyYFFQg==.ZVrm5iSrNNE2InxLqL6D0zpfmcoO0IDDMnAzKQXFxNu6T05rsV+ulNZSU02gqiQltoGyMBl6HorGFmVsWImWw5x0gB2lk7l/gH1Aqb5/5d/lR69l0b0uOOBMoBwlgbsgSg2Uzk+3WqKdAwpRp06TWJCwYDW8unf09Sj7feh0eQsoHDf/a+d7Hq9yW/0FSbOMOI0VEKcqtEYyzFD9DWcjgwDK1s6eM9+on1XDi9LhaxckLk8WYJVkXTBH9Yme8ymxzGOMdeeGfvkPFCcsSmxD/T14lM6mbDKUDS6YppItquJ9WgAdo/bqdTcGL8I4qfL7COVZ7Igz2wo3KgOCkhL9VkxICC7T8iJd13D1HsLX1yTxrsYIkXBNlu+LdLgsacWb/JEvVQJBVqQ9GZLgomVJP4YJkwPn
