### ISSUE TITLE
DENIED ACCESS

### ISSUE THREAD

**Issue by krispcodee** [noahcoolboy/funcaptcha#29]
![image](https://user-images.githubusercontent.com/72629742/214133583-f35b1912-4cbd-4cfd-8a87-a138eda7b6be.png)
![image](https://user-images.githubusercontent.com/72629742/214134600-a28ef07a-4f39-40b7-834a-99eca3535787.png)

Getting this when I attempt to signup. Yes I am passing a blob. Im using it with proxies. Did some searching and didnt find much,

**Comment by noahcoolboy** [comment]
Try adding a delay before using getToken
This happens because arkose labs rejects anything using an incorrect blob, and arkose labs isnt able to register the blob in te
The delay should be around 1-2 seconds
