### ISSUE TITLE
ACCESS_DENIED When using roblox login Public_key

### ISSUE THREAD

**Issue by Oli2004** [noahcoolboy/funcaptcha#32]
![image](https://user-images.githubusercontent.com/30935873/217055779-35645a90-2df5-4311-8a45-7fd4cb3a2795.png)

476068BF-9607-4799-B53D-966BE98E2B81

I tried many thing to try to fix it but none of them worked. This issue only happens on that key and doesn't happen on any other public_key. Could it be possible to try to figure out a way to fix this. thank you.

**Comment by IntangibleTrapazoid** [comment]
https://github.com/noahcoolboy/funcaptcha/issues/26
