### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zachariapopcorn** [noahcoolboy/funcaptcha#4]
I have a few questions for this package

Is this the updated version of roblox-funcaptcha?

Will this package continue to be updated?

Will you ever add an ability for getting the data[blob] value?

**Comment by noahcoolboy** [comment]
Hello! Thank you for your interest in my package
To answer your questions:
1. Yes, this is a continuation to the roblox-funcaptcha library. I realized that limiting it to roblox shouldn't be a thing, and also wanted autocompletion in my editor, so I decided to recreate it in typescript with support for other websites.
2. I will make efforts to try and keep this library functional, but I may lose motivation at one point.
3. data[blob] isn't a thing managed by funcaptcha. I assume you are trying to solve roblox captchas? In that case, you will find the blob in the fieldData once you get the "You must pass the robot test" error.
