### ISSUE TITLE
funcaptcha for browser

### ISSUE THREAD

**Issue by seteri** [noahcoolboy/funcaptcha#42]
after a lot of struggle, I finally figured out how to use funcaptcha for roblox login api, but now, instead of node environment, I want to use it in browser. I made a few changes and only thing I am importing is funcaptcha library itself and thats the only problem I face, I think browser does not support it or something ... can anyone suggest me what to do? I also tried using funcaptcha cdn, but it says: Uncaught ReferenceError: exports is not defined

**Comment by noahcoolboy** [comment]
The funcaptcha library is not designed for use in a browser, and it will not work when attempted either.
This project uses libraries such as crypto or undici which are designed for nodejs, so loading it elsewhere will most likely not work.

I will not be creating a separate version for this. You should most likely use getEmbedUrl for this type of task.
You are free to create your own for with compatibilty for browsers.
