### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by Kaiddd** [noahcoolboy/funcaptcha#44]
[funcaptcha.webm](https://github.com/noahcoolboy/funcaptcha/assets/37759450/2cf8e172-09ef-480d-87f1-6a1c0072782d)

Am I doing something wrong here? Or is this just not working?

I also cannot get embed urls to work either, which was my original plan

**Comment by seteri** [comment]
well, I could not make it work too, so I just use images I get in my node environment, I use canvas do crop them in equal peaces and create clone of verification page. Also u will need to create a simple function which rotates images ( just moves to another cropped image ), and thats pretty much it. after u press submit u should send current image number to ur backend server and if its correct, u can pass captcha

**Comment by seteri** [comment]
if u have come up with a better idea tell me

**Comment by noahcoolboy** [comment]
Issue unrelated to library

You are incorrectly sending captcha information to roblox.
By using an HTTP interception tool like fiddler, you will quickly discover roblox submits the token using the rblx-challenge-metadata header.
When submitting a token, the metadata is not the same in the request as the metadata in the response of the previous request.
It should be a base64 string containing the following data (in the case of roblox signup)
`{"unifiedCaptchaId":"CAPTCHAIDHERE","captchaToken":"CAPTCHATOKENHERE","actionType":"Signup"}`

**Comment by Kaiddd** [comment]
After I complete a captcha using the library, how would I get the needed headers to send the request?

**Comment by Kaiddd** [comment]
Never figured this out, no
