### ISSUE TITLE
cannot use proxies with auth

### ISSUE THREAD

**Issue by Wattville** [noahcoolboy/funcaptcha#45]
Error:
`
Proxy response !== 200 when HTTP Tunneling
`

Stack: 
`
AbortError: Proxy response !== 200 when HTTP Tunneling
    at Client.connect (C:\Users\Owner\Documents\node-projects\test\node_modules\undici\lib\proxy-agent.js:103:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
`

Works without proxies, proxy provider: https://proxyempire.io/

**Comment by noahcoolboy** [comment]
This may be one of 2 things:
1. Make sure the proxy url follows the proper format `http://username:password@host:port`
2. This may be an issue with your proxy provider, either blocking arkose labs or having improper authentication
