### ISSUE TITLE
challenge.instruction

### ISSUE THREAD

**Issue by lokazoha** [noahcoolboy/funcaptcha#48]
challenge.instruction is "undefined"

**Comment by noahcoolboy** [comment]
Would you mind providing the `challenge.data` object?
It's possible the instruction wasn't found in the places the code looks for.

**Comment by lokazoha** [comment]
Hopefully this does not contain any sensitive information..

`{
  session_token: '375178333022fbe66.2529907405',
  challengeID: '19364fc4391dd5006.8220061105',
  challengeURL: 'https://roblox-api.arkoselabs.com/fc/assets/match-game-ui/0.33.0/standard/index.html',
  audio_challenge_urls: null,
  audio_game_rate_limited: null,
  sec: 30,
  end_url: null,
  game_data: {
    display_fc_welldone: false,
    final_challenge_text: '',
    customGUI: {
      example_images: [Object],
      _challenge_imgs: [Array],
      _final_chal_lang_key: 'touch_done_info_colour',
      _disableFinalChalAfterSecChal: 1,
      fc2_rotate_stroke: 0,
      _guiProgressColorSecondary: '#f8fdff',
      _guiTaper: 0,
      _meta_bg_colour: 'transparent',
      _guiBGColorMain: '#ffffff',
      fc2_button_small: 1,
      _guiInfoText: '#474747',
      _guiTextColor: '#474747',
      _landingTextColor: '#868686',
      _guiNoShadow: 1,
      _guiProgressTextColor: '#474747',
      _guiTheme: 3,
      _guiProgressColorMain: '#f8fdff',
      fc2_button_taper: 0,
      fc2_text_bg: '#ffffff',
      _guiColorMain: '#3FC679',
      _guiNoInfoBG: 1,
      fc2_stroke_colour: '#ffffff',
      fc2_button_border_thickness: 1,
      fc2_rotate_bg: 0,
      _guiNoOutline: 1,
      fc2_stroke_size: 1,
      _intro_game_bg: 0,
      fc2_button_font_size: 17,
      _guiColorSecondary: '#3FC679',
      fc2_button_text_colour: '#ffffff',
      _guiBGColorSecondary: '#ffffff',
      _guiLoaderColor: '#3FC679',
      _meta_icon_colour: '#757575',
      _meta_theme: '3',
      watermark_not_for_public: 0,
      api_breaker: [Object],
      api_breaker_v2_enabled: 1,
      is_using_api_breaker_v2: true,
      _final_ball: null,
      _app_bg: 'https://roblox-api.arkoselabs.com/cdn/fc/assets/graphics/funcaptcha/004/white.png',
      _end_banner: 'https://roblox-api.arkoselabs.com/cdn/fc/assets/graphics/roblox/roblox-victory-green2.jpg',
      embedded_session_id_enabled: 1,
      audio_disabled: false
    },
    waves: 6,
    instruction_string: 'dicematch',
    game_difficulty: 6,
    answer_width: 200,
    answer_height: 200,
    key_width: 125,
    key_height: 200,
    puzzle_name: 'Fraud Farm Dice',
    feature_game4_at_availability: true,
    gameType: 4,
    styling: { pick_a_tile: [Object] }
  },
  game_sid: 'eu-west-1',
  sid: 'eu-west-1',
  lang: 'en',
  string_table_prefixes: [ 'roblox_custom_instructions' ],
  string_table: {
    'meta.help': 'Get answers to your questions',
    '4.game_progress': '{{currentChallenge}} of {{numChallenges}}',
    '4.key_image_annotation': 'Match This!',
    'meta.audio_info_play-3': 'Press Play, type the number of the song that is the most sad, then press enter:',
    'meta.text_info': 'Enter the text you see:',
    'meta.footer_general_info': 'Play like humans do.',
    '4.fail_info_timed_top': 'That was not quite fast enough.',
    'meta.audio_info_ctrl': 'Press CTRL to play again.',
    'meta.star_info': 'Stars you have earned',
    'meta.visual_version': 'Change to a visual challenge',
    'aria.tick_icon_alt': 'Example for correct answer.',
    'meta.audio_sending_answer': 'Committing your answer. Please wait...',
    'game_meta.seconds': 'seconds',
    'meta.audio_play_again': 'Play sound again',
    'meta.audio_please_download_info': 'Please download and listen to the sound, then type what you heard:',
    'meta.audio_info': 'Enter the numbers you hear:',
    'meta.session_timeout': 'The connection to a verification server was interrupted. Please <strong>refresh this page</strong> to try again.',
    'meta.audio_info_play': 'Press Play and type what you hear:',
    'meta.footer_finished_info-1': "<p><strong>Verification complete!</strong></p><p>You've proven you're a human.</p><p>Continue your action.</p>",
    'meta.footer_finished_info-3': "<b>Verification complete!</b><br>You've proven you're a human.<br>Continue your action.",
    '4.fail_button': 'Try again',
    'meta.audio_play_button': 'Play',
    '4.interstitial_progress_2': '{{currentChallenge}} of {{numChallenges}}',
    '4.interstitial_progress_1': '{{currentChallenge}} done',
    'aria.correct_image_alt': 'Example for correct answer.',
    'meta.audio_new_puzzle': 'Start over with a different challenge',
    'meta.html_verify_info': "Please prove you're not a spammer by doing this quick activity!",
    '4.instructions-dicematch': 'Click the arrows to sum the dice and match the number on the left.',
    'game_meta.game_great': 'Great',
    'meta.funcaptcha_website': 'Open Arkose Labs website',
    'roblox_custom_instructions-game_meta.landing_info': 'Please solve this challenge so we know you are a real person',
    'aria.challenge_image_alt': 'Image {{count}}.',
    'roblox_custom_instructions_pair-game_meta.landing_start': 'Verify',
    'game_meta.verification': 'Verification',
    'aria.input_placeholder': 'Type here...',
    'meta.audio_sent_info': "Verification complete! You've proven you're a human. Continue your action.",
    'meta.funcaptcha': 'Arkose Labs',
    'meta.reload_challenge': 'Reload Challenge',
    'aria.left_arrow': 'Navigate to previous image',
    'meta.generic_error': 'Something went wrong. Please reload the challenge to try again.',
    'aria.audio_challenge': 'Audio challenge',
    'meta.audio_disabled': 'The audio challenge has been disabled. Please use the visual challenge, or contact the customer support team for assistance.',
    '4.challenge_progress': '{{currentChallenge}} of {{numChallenges}}',
    'meta.stars_link': 'Stars',
    'meta.api_timeout_error': 'The connection to a verification server was interrupted. Please reload the challenge to try again. ',
    'aria.right_arrow': 'Navigate to next image',
    'meta.audio_challenge_frame_title': 'Audio challenge',
    'aria.visual_challenge_describe': 'Audio challenge is available below. Compatible with screen reader software.',
    '4.hint-dicematch': 'Make sure that the dice add up to match the image on the left.',
    'meta.audio_version': 'Change to an audio challenge',
    'meta.audio_answer_input': 'Challenge Answer',
    'meta.audio_challenge': 'Change to an audio challenge',
    'meta.footer_patent': 'Patent pending',
    '4.submit_button': 'Submit',
    'game_meta.checking': 'Checking',
    'game_meta.game_good': 'Good',
    'aria.answer_field': 'Answer field',
    '4.hint': 'Make sure to select an image that matches what you see in the example image.',
    'meta.audio_verify_button': 'Verify',
    'meta.audio_play': 'Play Sound',
    'meta.audio_please_download_info-3': 'Please download and listen to the sound, type the number of the song that is the most sad:',
    '4.intro_title': 'Verification',
    'meta.audio_alert': 'Please enter your answer into the input box.',
    'meta.loading_info': 'Working, please wait...',
    'aria.audio_answer_input': 'Challenge answer',
    'meta.html_verify_button': 'Verify',
    'meta.meta_start_cta': 'Start visual challenge',
    'meta.footer_general_info-1': 'Please solve the puzzle.',
    'game_meta.challenge': 'Challenge {{count}}',
    '4.instructions': '<strong>Press the arrows</strong> to see different images. When the image <strong>matches the example</strong> on the left, press Submit!',
    '4.fail_info_timed_middle_hidden': 'Try to answer before too much time runs out!',
    'roblox_custom_instructions-game_meta.landing_heading': 'Verification',
    'game_meta.not_for_public_watermark': 'NOT FOR PRODUCTION USE',
    'game_meta.interstitial_progress_1': '{{currentChallenge}} done',
    'meta.funcaptcha_solved_phrase': 'Verification challenge has been solved',
    'game_meta.wait_text': 'Please wait while we check your score.',
    'aria.visual_challenge_label': 'Visual challenge.',
    'game_meta.landing_heading': 'Protecting your account',
    'meta.verification_complete': 'Verification complete!',
    'aria.cross_icon_alt': 'Example for incorrect answer.',
    'aria.wrong_image_alt': 'Example for incorrect answer.',
    'aria.restart_challenge': 'Restarting challenge',
    'meta.audio_rate_limit': 'Use of the audio challenge for this user has been too high. Please try again.',
    'meta.restart_label': 'Restart',
    'meta.audio_incorrect': 'Incorrect, try again',
    'game_meta.landing_info': 'Please solve this puzzle so we know you are a real person',
    '4.fail_top': 'That was not quite right.',
    'game_meta.game_perfect': 'Perfect',
    'roblox_custom_instructions_pair-3.instructions': 'Pick the image with matching items',
    '4.finish_message': "<b>Verification Complete</b> <br>You've proven you're a human. <br>Continue your action.",
    'meta.audio_challenge_label': 'Audio',
    'meta.finished_info': "You've proven you're a human. Continue your action.",
    'meta.footer_phone_mode_on': "This isn't working for me",
    'game_meta.game_check': 'Check!',
    'meta.session_reset': 'Your session was reset. Please try again.',
    'game_meta.landing_button': 'Verify',
    'aria.visual_challenge': 'Visual challenge. Audio challenge is available below, compatible with screen reader software.',
    'meta.visual_challenge_label': 'Visual',
    'meta.visual_challenge_frame_title': 'Visual challenge',
    'game_meta.landing_start': 'Start Puzzle',
    'meta.audio_download': 'Download Sound'
  },
  earlyVictoryMessage: null,
  font_size_adjustments: null,
  style_theme: 'default',
  token: 'token=375178333022fbe66.2529907405|r=eu-west-1|meta=3|metabgclr=transparent|metaiconclr=%23757575|maintxtclr=%23b8b8b8|guitextcolor=%23474747|lang=en|pk=A2A14B1D-1AF3-C791-9BBC-EE33CC7A0A6F|at=40|ag=101|cdn_url=https%3A%2F%2Froblox-api.arkoselabs.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-eu-west-1.arkoselabs.com|surl=https%3A%2F%2Froblox-api.arkoselabs.com|smurl=https%3A%2F%2Froblox-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager',
  tokenInfo: {
    token: '375178333022fbe66.2529907405',
    r: 'eu-west-1',
    meta: '3',
    metabgclr: 'transparent',
    metaiconclr: '#757575',
    maintxtclr: '#b8b8b8',
    guitextcolor: '#474747',
    lang: 'en',
    pk: 'A2A14B1D-1AF3-C791-9BBC-EE33CC7A0A6F',
    at: '40',
    ag: '101',
    cdn_url: 'https://roblox-api.arkoselabs.com/cdn/fc',
    lurl: 'https://audio-eu-west-1.arkoselabs.com',
    surl: 'https://roblox-api.arkoselabs.com',
    smurl: 'https://roblox-api.arkoselabs.com/cdn/fc/assets/style-manager',
    mbio: true
  }
}`

**Comment by noahcoolboy** [comment]
Issue fixed in latest version.
Thanks for reporting.
