### ISSUE TITLE
Got {"response":"not answered","decryption_key":"...

### ISSUE THREAD

**Issue by soul1229** [noahcoolboy/funcaptcha#51]
1. Got a task with type "3"
2. Sent a number between 0 and 5 as an answer.
3. Got this response:

` {"response":"not answered","decryption_key":"73465047f4e6e4a35.7183978505","time_end":1694793619,"time_end_seconds":59}
`

When I've answered all the waves I get a response:

`{"response":"answered","solved":false,"incorrect_guess":"","score":3,"decryption_key":null,"time_end":1694793901,"time_end_seconds":59}`

What could it possibly mean?

**Comment by noahcoolboy** [comment]
This is expected. "not answered" simply means you haven't finished the captcha yet. "answered" means you're done with it, and you can use the `solved` property to know if you've answered all the waves correctly or not.
