### ISSUE TITLE
Challenge failed to authorize request

### ISSUE THREAD

**Issue by Lennon2563** [noahcoolboy/funcaptcha#58]
Hello the captcha is updated again the captcha is longer working anymore in roblox login api i says
"Challenge failed to authorize request"

**Comment by noahcoolboy** [comment]
This is something I am currently looking into.
The cause is unclear as of now.

**Comment by Lennon2563** [comment]
its fix now by adding https://apis.roblox.com/challenge/v1/continue

**Comment by noahcoolboy** [comment]
Thanks for the info.
I'm assuming this isn't a problem with the library then, I'll be closing the issue now.

**Comment by ghost1006** [comment]
@Lennon2563 Hi there! Could you please share some guidance on using the API? I've been trying for a few hours now, and I keep encountering either error 500 (internal server error) or error 400 (bad request). I've used dev tools on firefox and chrome yet, still I get these errors even though the headers and the body seems right. I appreciate your help in advance, and I'm sorry for bringing this issue up again.
