### ISSUE TITLE
Roblox signup API error: Challenge failed to authorize request (Invalid captchas?)

### ISSUE THREAD

**Issue by ghost1006** [noahcoolboy/funcaptcha#60]
Hello there!
I've encountered an issue with the Roblox signup API, specifically related to captcha challenges. It used to work perfectly for me, but recently, I've been consistently receiving the following error message: "Challenge failed to authorize request."
Is there any fix available for this issue? I'd greatly appreciate your assistance in resolving this matter.
Thank you in advance!

**Comment by noahcoolboy** [comment]
Issue unrelated to library and already resolved in previous issue.
https://github.com/noahcoolboy/funcaptcha/issues/58#issuecomment-1731410032
Make a call to https://apis.roblox.com/challenge/v1/continue, you can find the body and headers you need to send using any http debugging tool.
