### ISSUE TITLE
decryption_key ???

### ISSUE THREAD

**Issue by elpolar** [noahcoolboy/funcaptcha#62]
Hello Sir, am Polar.
Let me tell you my THANKS for creating this proyect and i hope you can conitnue helping us with such a great proyects as this. really, my REAL THANKS to you. I can donate or anything just for you to cotinue taking care of this proyect, this not a problem.
OK, my question is this.
I am triying to solve the public_key, and as you can see in the image each awnser i send i receive a "decryption_key" , is this something i am able to bypass? or how do i figure it out this? its possible for you to give me some kind of HINT?? Just a little hint. I will catch it np.
![image](https://github.com/noahcoolboy/funcaptcha/assets/128242030/7ffa6567-823e-4b2b-9db7-4eea3757a5f0)

**Comment by elpolar** [comment]
OHHHHH.... the "decryption_key" its used to decrypt the image, so its nothing to worry about because we already getting the captcha image. So this its good. The only trouble its the "timed_mode_timeout".

I set a delay for 1500ms on each response send? and still showing the same same.

**Comment by noahcoolboy** [comment]
Hi!

I believe you are getting timed out because you are either taking too much time (more than 20 seconds) or have incorrectly set the captcha parameters. Using an incorrect public key or blob may cause the captcha to load but silently be unsolvable.

Please show me which configuration you are using (what parameters are you passing to getToken) and for which website you are doing this.

**Comment by elpolar** [comment]
> Hi!
> 
> I believe you are getting timed out because you are either taking too much time (more than 20 seconds) or have incorrectly set the captcha parameters. Using an incorrect public key or blob may cause the captcha to load but silently be unsolvable.
> 
> Please show me which configuration you are using (what parameters are you passing to getToken) and for which website you are doing this.
> 
> The encryption key is nothing to worry about and is used only for images.

![image](https://github.com/noahcoolboy/funcaptcha/assets/128242030/3ea3e9c9-b102-4f31-9beb-1c935772c8d7)

Am pretty sure i am getting the good BLOB because this function was beeing used for another service like 2captcha, etc. and allways worked. Hmmm, i am setting 2000ms each awnser i send to funcaptcha:
![image](https://github.com/noahcoolboy/funcaptcha/assets/128242030/e2266d62-cbff-4a91-a9a9-6366e6e990bf)


I already tryed without blob, on 200ms waiting time, 500ms, 1000ms. with user-agent, without user-agent. Hmmmmm....

**Comment by elpolar** [comment]
![image](https://github.com/noahcoolboy/funcaptcha/assets/128242030/d5c6391a-b735-4340-83d8-6d74f5eac503)

This its my current config and seems like its appearing more frecuentrly the normal result. but not solved. I mean, its not showing the time_limit thing.. Hmmm, the only left params i need to use its the proxy. i will try in few, but hope its the proxy and not something more difficult on find...

**Comment by noahcoolboy** [comment]
From what I can see in your last screenshot you finished the captcha successfully, but solved is equal to false meaning one of the answers was incorrect.

**Comment by elpolar** [comment]
Am pretty sure i am sending the right anwsers. Manually and automatic. However, the result its the same.

**Comment by elpolar** [comment]
The problem was the blob. many thanks.

**Comment by Oli2004** [comment]
> ![image](https://user-images.githubusercontent.com/128242030/270379065-d5c6391a-b735-4340-83d8-6d74f5eac503.png)
> 
> This its my current config and seems like its appearing more frecuentrly the normal result. but not solved. I mean, its not showing the time_limit thing.. Hmmm, the only left params i need to use its the proxy. i will try in few, but hope its the proxy and not something more difficult on find...

i also have made an api to use xevil and this library to solve funcaptcha. but i have to substract 1 from what xevil returns or else it does not work. xevil counts the images strating from 1 and no 0
