### ISSUE TITLE
got incorrect image content

### ISSUE THREAD

**Issue by crazysvn** [noahcoolboy/funcaptcha#67]
I'm making a java program in which some codes are converted from your codes.
I got image challenge link like this:
https://client-api.arkoselabs.com/rtig/image?challenge=0&sessionToken=181178b72054e7a76.6422117304&gameToken=487651fae5129f606.3536452704
but downloaded image content is like this:
{"ct":"5kwKT4XeECXNIF+A7...........","iv":"2496f3b6bcb223734ee448fc13fff319","s":"1f78c5e0937472ba"}
do you have any idea where I might be wrong?

**Comment by noahcoolboy** [comment]
It's an encrypted image
see crypt.ts and challenge.ts
