### ISSUE TITLE
Unable to solve captchas in browser

### ISSUE THREAD

**Issue by zachariapopcorn** [noahcoolboy/funcaptcha#7]
Heya! I'm trying to implement a feature for a project that requires users to solve captchas in the browser. However, when I try to test it, I keep on getting stuck on the captcha loading screen. Am I doing something wrong? Here is my code

```js
const fun = require("funcaptcha");

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'

fun.getToken({
    pkey: "476068BF-9607-4799-B53D-966BE98E2B81",
    surl: "https://roblox-api.arkoselabs.com",
    headers: {
        "User-Agent": UA
    }
}).then(async(token) => {
    let s = new fun.Session(token, {userAgent: UA});
    console.log(s.getEmbedUrl());
});
```

**Comment by noahcoolboy** [comment]
How are you displaying the captcha to the user?
Simply sending the embed URL will not work as these are designed to be embedded in an iframe
It won't load unless put in an iframe

**Comment by zachariapopcorn** [comment]
Well, the project is a Discord bot, and I thought that sending the embed url would be easier for the user to solve. Is there a way for me to do this with the embed url, or should I just use the getImage() function?

**Comment by noahcoolboy** [comment]
Ah
Unfortunately it is impossible to get the embed working without it being in an iframe
You can either create a small website whicj puts the embed URL in an iframe le you can make the user solve the captcha directly in discord

**Comment by zachariapopcorn** [comment]
Ah, that sucks, thank you for answering
