### ISSUE TITLE
How to create data[blob]

### ISSUE THREAD

**Issue by phuonglazy** [noahcoolboy/funcaptcha#70]
The data[blob] string is created from the server, can you find a way to create this string yourself? Currently, funcaptcha is improving the limitation of token creation without the data[blob] string.
For example, previously I could create a funcaptcha hotmail solver token without getting {"error":"DENIED ACCESS"}, but now creating a token requires data[blob] and it can only be used once. inconvenient if running in large quantities.
Thanks

**Comment by noahcoolboy** [comment]
The blob cannot be created by you. It is encrypted with an encryption and decryption key only know by the service and arkose labs. You will have to find a way to get it from the service you are trying to solve a captcha for.
