### ISSUE TITLE
New TGUESS Parameter for Game Type 4

### ISSUE THREAD

**Issue by mahelbir** [noahcoolboy/funcaptcha#73]
Hi new post parameter added for gameType 4 in /ca request (answering) . It includes answer index and session Token splitted by dot. Twitter denies answers without "tguess". (Invalid captcha). Also it is encrypted with murmur. Body: JSON Array, Key: sessionToken

There are several types I see. For 3d_rollball_animals with 1 wave:

Session Token: 359178d184d4bd2d2.6842749205
`[
    {
        "index": "4",
        "359178d184d4bd2d2": "6842749205"
    }
]`

`[{"index":1,"578178d18fdb43377":"5979016405"}]`
`[{"index":5,"107178d1901472b81":"8487087105"}]`

rat_maze with 5 waves:
`[
    {
        "index": "0",
        "789178d1a274d2b43": "8616045605",
        "indextr": "048",
        "789178d1a274d2b43tr": "056495454485352545348"
    },
    {
        "index": "1",
        "789178d1a274d2b43": "8616045605",
        "indextr": "049",
        "789178d1a274d2b43tr": "056495454485352545348"
    },
    {
        "index": "0",
        "789178d1a274d2b43": "8616045605",
        "indextr": "048",
        "789178d1a274d2b43tr": "056495454485352545348"
    },
    {
        "index": "2",
        "789178d1a274d2b43": "8616045605",
        "indextr": "050",
        "789178d1a274d2b43tr": "056495454485352545348"
    }
]`

`[
    {
        "index": "0",
        "651178d1a58de4174": "4294279605",
        "indextr": "048",
        "651178d1a58de4174tr": "052575750525554535048"
    }
]`

**Comment by luckywangxi** [comment]
> Hi new post parameter added for gameType 4 in /ca request (answering) . It includes answer index and session Token splitted by dot. Twitter denies answers without "tguess". (Invalid captcha). Also it is encrypted with murmur. Body: JSON Array, Key: sessionToken
> 
> There are several types I see. For 3d_rollball_animals with 1 wave:
> 
> Session Token: 359178d184d4bd2d2.6842749205 `[ { "index": "4", "359178d184d4bd2d2": "6842749205" } ]`
> 
> `[{"index":1,"578178d18fdb43377":"5979016405"}]` `[{"index":5,"107178d1901472b81":"8487087105"}]`
> 
> rat_maze with 5 waves: `[ { "index": "0", "789178d1a274d2b43": "8616045605", "indextr": "048", "789178d1a274d2b43tr": "056495454485352545348" }, { "index": "1", "789178d1a274d2b43": "8616045605", "indextr": "049", "789178d1a274d2b43tr": "056495454485352545348" }, { "index": "0", "789178d1a274d2b43": "8616045605", "indextr": "048", "789178d1a274d2b43tr": "056495454485352545348" }, { "index": "2", "789178d1a274d2b43": "8616045605", "indextr": "050", "789178d1a274d2b43tr": "056495454485352545348" } ]`
> 
> `[ { "index": "0", "651178d1a58de4174": "4294279605", "indextr": "048", "651178d1a58de4174tr": "052575750525554535048" } ]`

Hi! Is it available in python? 
I don't know how to submit answer in python code, 
here is my code, I use the [funcaptcha](https://github.com/noahcoolboy/funcaptcha/tree/master)/[lib](https://github.com/noahcoolboy/funcaptcha/tree/master/lib/crypt.js)
 to encrypt it.
`            answer_data = f'[{{"index": {answer}}}]'
            print(answer_data)
            guess = encrypt(answer_data, session_token)
            print('guess', guess)`

it always shows 'not answered', even my answers are all right in funcapcha game 4 not V2

`[{"index": 2}]
guess {"ct":"D+1JrxSOFJ0vid5nVsTWPQ==","iv":"6a8a2409a80e9db1de1580e77f7399ab","s":"6972716c636d6d78"}
{"response":"not answered"}`

Thank You!

**Comment by mahelbir** [comment]
Any news?

**Comment by 760644586** [comment]
The change in tguesses in version 2.3.1 is not a session token
