### ISSUE TITLE
how would i go about actually getting the captcha token?

### ISSUE THREAD

**Issue by brandoge91** [noahcoolboy/funcaptcha#8]
im successfully sending the roblox funcaptcha and displaying it on a website and solving it, but how would i get the actual captcha token to provide to the login API? Sorry if this is a dumb question and is easier  hen i thought!

**Comment by brandoge91** [comment]
closed, im dumb lol,

**Comment by noahcoolboy** [comment]
getToken returns an object (a GetTokenResult interface if you're using typescript)
It has a property called token, which is a string

If you instead want to get the token from the session, you can use the Session.token property
