### ISSUE TITLE
Add string_table property to challenges

### ISSUE THREAD

**Issue by zachariapopcorn** [noahcoolboy/funcaptcha#9]
Hello, I'm requesting that you add the string_table property in challenges, as it appears like there's a property like that in the challenge pastebin that you provide. Either that, or a method that converts a game_variant to an objective

**Comment by noahcoolboy** [comment]
Hello again
The pastebin which I provided is an example of what you can find in the Challenge.data object
Meaning that, the string_table is accessible using Challenge.data.string_table
If you would like the instruction string, you can use `captcha.data.string_table[\`${captcha.data.game_data.gameType}.instructions-${captcha.data.game_data.game_variant}\`]`

**Comment by zachariapopcorn** [comment]
Yea I'm using Typescript, and I thought doing // @ts-ignore does that for the whole file, no?

**Comment by noahcoolboy** [comment]
// @ts-ignore only ignores the next line, while // @ts-nocheck does it for the whole file
At least that's what I think

**Comment by noahcoolboy** [comment]
The properties have been added
As a bonus, there is now an `instruction` accessor in the Challenge class which will directly give you the instruction string
